name: AllAPILoader
main: BeckenPlayZMCPE\AllAPILoader\Main
version: 4.0.0
api: [3.3.4]
author: BeckenPlayZMCPE
description: Makes the server load every plugin regardless of the API version
load: STARTUP
softdepend: ["DevTools", "FolderPluginLoader"]
